name: Pack

on:
  push:
    branches: [ master ]
    
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Tar and encrypt
        run: tar -czvf - -C ../ ./dotfiles | openssl des3 -salt -k password -out dotfiles.tar.gz

      - uses: actions/upload-artifact@v2
        name: Upload to artifact
        with:
          name: dotfiles.tar.gz
          path: dotfiles.tar.gz

      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
